version: '3.8'

services:
  web:
    build: .
    container_name: webgacha-indiraise
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # biar Jenkins bisa akses Docker host
      - /usr/bin/docker:/usr/bin/docker             # biar Jenkins bisa build image Docker
    privileged: true

volumes:
  jenkins_home:
